language: php

php:
- 7.1.9

services:
- mysql

#database tables are created by travis with the stuff in .env
before_script:
- cd soen341-UB3-QA
- composer self-update
- composer install --no-interaction
- mysql -e 'CREATE DATABASE IF NOT EXISTS projectub3;'
- cp .env.example .env
- php artisan migrate
- php artisan key:generate

script:
- vendor/bin/phpunit
